resources:
  repositories:
    - repository: templates
      type: github
      name: Croydon/templates
      endpoint: Croydon

jobs:
- template: .ci/azure.yml@templates
  parameters:
    vsVersions: "14,16"
    appleClangVersions: ""
