version: 2
.conan-steps: &conan-steps
  parallelism: 4
  steps:
    - checkout
    - run:
        name: Update Conan package
        command: |
          sudo apt purge python-pip
          sudo apt-get update && sudo apt-get install -y python3 python3-pip
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 2
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 3
          sudo update-alternatives  --set python /usr/bin/python3
          chmod +x .ci/install.sh
          .ci/install.sh
    - run:
        name: Build recipe
        command: |
          export CONAN_CURRENT_PAGE=$((${CIRCLE_NODE_INDEX}+1))
          export CONAN_TOTAL_PAGES=${CIRCLE_NODE_TOTAL}
          chmod +x .ci/run.sh
          .ci/run.sh

jobs:
  android-x86:
    docker:
      - image: circleci/android:api-28
    environment:
      - CONAN_BUILD_REQUIRES: android_ndk_installer/r20@bincrafters/stable
      - CONAN_ARCHS: x86_64,x86
      - ONAN_CLANG_VERSIONS: 8
    <<: *conan-steps

  android-arm:
    docker:
      - image: circleci/android:api-28
    environment:
      - CONAN_BUILD_REQUIRES: android_ndk_installer/r20@bincrafters/stable
      - CONAN_ARCHS: armv7,armv8
      - ONAN_CLANG_VERSIONS: 8
    <<: *conan-steps

  gcc-49:
    docker:
      - image: conanio/gcc49
    environment:
      - CONAN_GCC_VERSIONS: "4.9"
    <<: *conan-steps

  gcc-5:
    docker:
      - image: conanio/gcc5
    environment:
      - CONAN_GCC_VERSIONS: "5"
    <<: *conan-steps

  gcc-6:
    docker:
      - image: conanio/gcc6
    environment:
      - CONAN_GCC_VERSIONS: "6"
    <<: *conan-steps

  gcc-7:
    docker:
      - image: conanio/gcc7
    environment:
      - CONAN_GCC_VERSIONS: "7"
    <<: *conan-steps

  gcc-8:
    docker:
      - image: conanio/gcc8
    environment:
      - CONAN_GCC_VERSIONS: "8"
    <<: *conan-steps

  clang-39:
    docker:
      - image: conanio/clang39
    environment:
      - CONAN_CLANG_VERSIONS: "3.9"
    <<: *conan-steps

  clang-40:
    docker:
      - image: conanio/clang40
    environment:
      - CONAN_CLANG_VERSIONS: "4.0"
    <<: *conan-steps

  clang-50:
    docker:
      - image: conanio/clang50
    environment:
      - CONAN_CLANG_VERSIONS: "5.0"
    <<: *conan-steps

  clang-60:
    docker:
      - image: conanio/clang60
    environment:
      - CONAN_CLANG_VERSIONS: "6.0"
    <<: *conan-steps


workflows:
  version: 2
  build_and_test:
    jobs:
      - android-x86
      - android-arm