version: 2
.conan-steps: &conan-steps
  steps:
    - checkout
    - run:
        name: Update Conan package
        command: |
          chmod +x .ci/install.sh
          .ci/install.sh
    - run:
        name: Build recipe
        command: |
          chmod +x .ci/run.sh
          .ci/run.sh

jobs:
  gcc-49-page-1:
    docker:
      - image: conanio/gcc49
    environment:
      - CONAN_GCC_VERSIONS: "4.9"
      - CONAN_CURRENT_PAGE: 1
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-49-page-2:
    docker:
      - image: conanio/gcc49
    environment:
      - CONAN_GCC_VERSIONS: "4.9"
      - CONAN_CURRENT_PAGE: 2
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-49-page-3:
    docker:
      - image: conanio/gcc49
    environment:
      - CONAN_GCC_VERSIONS: "4.9"
      - CONAN_CURRENT_PAGE: 3
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-49-page-4:
    docker:
      - image: conanio/gcc49
    environment:
      - CONAN_GCC_VERSIONS: "4.9"
      - CONAN_CURRENT_PAGE: 4
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-49-page-5:
    docker:
      - image: conanio/gcc49
    environment:
      - CONAN_GCC_VERSIONS: "4.9"
      - CONAN_CURRENT_PAGE: 5
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-49-page-6:
    docker:
      - image: conanio/gcc49
    environment:
      - CONAN_GCC_VERSIONS: "4.9"
      - CONAN_CURRENT_PAGE: 6
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-49-page-7:
    docker:
      - image: conanio/gcc49
    environment:
      - CONAN_GCC_VERSIONS: "4.9"
      - CONAN_CURRENT_PAGE: 7
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-49-page-8:
    docker:
      - image: conanio/gcc49
    environment:
      - CONAN_GCC_VERSIONS: "4.9"
      - CONAN_CURRENT_PAGE: 8
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps

  gcc-5-page-1:
    docker:
      - image: conanio/gcc5
    environment:
      - CONAN_GCC_VERSIONS: "5"
      - CONAN_CURRENT_PAGE: 1
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-5-page-2:
    docker:
      - image: conanio/gcc5
    environment:
      - CONAN_GCC_VERSIONS: "5"
      - CONAN_CURRENT_PAGE: 2
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-5-page-3:
    docker:
      - image: conanio/gcc5
    environment:
      - CONAN_GCC_VERSIONS: "5"
      - CONAN_CURRENT_PAGE: 3
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-5-page-4:
    docker:
      - image: conanio/gcc5
    environment:
      - CONAN_GCC_VERSIONS: "5"
      - CONAN_CURRENT_PAGE: 4
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-5-page-5:
    docker:
      - image: conanio/gcc5
    environment:
      - CONAN_GCC_VERSIONS: "5"
      - CONAN_CURRENT_PAGE: 5
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-5-page-6:
    docker:
      - image: conanio/gcc5
    environment:
      - CONAN_GCC_VERSIONS: "5"
      - CONAN_CURRENT_PAGE: 6
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  ggcc-5-page-7:
    docker:
      - image: conanio/gcc5
    environment:
      - CONAN_GCC_VERSIONS: "5"
      - CONAN_CURRENT_PAGE: 7
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-5-page-8:
    docker:
      - image: conanio/gcc5
    environment:
      - CONAN_GCC_VERSIONS: "5"
      - CONAN_CURRENT_PAGE: 8
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps

  gcc-6-page-1:
    docker:
      - image: conanio/gcc6
    environment:
      - CONAN_GCC_VERSIONS: "6"
      - CONAN_CURRENT_PAGE: 1
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-6-page-2:
    docker:
      - image: conanio/gcc6
    environment:
      - CONAN_GCC_VERSIONS: "6"
      - CONAN_CURRENT_PAGE: 2
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-6-page-3:
    docker:
      - image: conanio/gcc6
    environment:
      - CONAN_GCC_VERSIONS: "6"
      - CONAN_CURRENT_PAGE: 3
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-6-page-4:
    docker:
      - image: conanio/gcc6
    environment:
      - CONAN_GCC_VERSIONS: "6"
      - CONAN_CURRENT_PAGE: 4
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-6-page-5:
    docker:
      - image: conanio/gcc6
    environment:
      - CONAN_GCC_VERSIONS: "6"
      - CONAN_CURRENT_PAGE: 5
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-6-page-6:
    docker:
      - image: conanio/gcc6
    environment:
      - CONAN_GCC_VERSIONS: "6"
      - CONAN_CURRENT_PAGE: 6
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-6-page-7:
    docker:
      - image: conanio/gcc6
    environment:
      - CONAN_GCC_VERSIONS: "6"
      - CONAN_CURRENT_PAGE: 7
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-6-page-8:
    docker:
      - image: conanio/gcc6
    environment:
      - CONAN_GCC_VERSIONS: "6"
      - CONAN_CURRENT_PAGE: 8
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps

  gcc-7-page-1:
    docker:
      - image: conanio/gcc7
    environment:
      - CONAN_GCC_VERSIONS: "7"
      - CONAN_CURRENT_PAGE: 1
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-7-page-2:
    docker:
      - image: conanio/gcc7
    environment:
      - CONAN_GCC_VERSIONS: "7"
      - CONAN_CURRENT_PAGE: 2
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-7-page-3:
    docker:
      - image: conanio/gcc7
    environment:
      - CONAN_GCC_VERSIONS: "7"
      - CONAN_CURRENT_PAGE: 3
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-7-page-4:
    docker:
      - image: conanio/gcc7
    environment:
      - CONAN_GCC_VERSIONS: "7"
      - CONAN_CURRENT_PAGE: 4
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-7-page-5:
    docker:
      - image: conanio/gcc7
    environment:
      - CONAN_GCC_VERSIONS: "7"
      - CONAN_CURRENT_PAGE: 5
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-7-page-6:
    docker:
      - image: conanio/gcc7
    environment:
      - CONAN_GCC_VERSIONS: "7"
      - CONAN_CURRENT_PAGE: 6
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-7-page-7:
    docker:
      - image: conanio/gcc7
    environment:
      - CONAN_GCC_VERSIONS: "7"
      - CONAN_CURRENT_PAGE: 7
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-7-page-8:
    docker:
      - image: conanio/gcc7
    environment:
      - CONAN_GCC_VERSIONS: "7"
      - CONAN_CURRENT_PAGE: 8
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps

  gcc-8-page-1:
    docker:
      - image: conanio/gcc8
    environment:
      - CONAN_GCC_VERSIONS: "8"
      - CONAN_CURRENT_PAGE: 1
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-8-page-2:
    docker:
      - image: conanio/gcc8
    environment:
      - CONAN_GCC_VERSIONS: "8"
      - CONAN_CURRENT_PAGE: 2
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-8-page-3:
    docker:
      - image: conanio/gcc8
    environment:
      - CONAN_GCC_VERSIONS: "8"
      - CONAN_CURRENT_PAGE: 3
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-8-page-4:
    docker:
      - image: conanio/gcc8
    environment:
      - CONAN_GCC_VERSIONS: "8"
      - CONAN_CURRENT_PAGE: 4
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-8-page-5:
    docker:
      - image: conanio/gcc8
    environment:
      - CONAN_GCC_VERSIONS: "8"
      - CONAN_CURRENT_PAGE: 5
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-8-page-6:
    docker:
      - image: conanio/gcc8
    environment:
      - CONAN_GCC_VERSIONS: "8"
      - CONAN_CURRENT_PAGE: 6
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-8-page-7:
    docker:
      - image: conanio/gcc8
    environment:
      - CONAN_GCC_VERSIONS: "8"
      - CONAN_CURRENT_PAGE: 7
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  gcc-8-page-8:
    docker:
      - image: conanio/gcc8
    environment:
      - CONAN_GCC_VERSIONS: "8"
      - CONAN_CURRENT_PAGE: 8
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps

  clang-39-page-1:
    docker:
      - image: conanio/clang39
    environment:
      - CONAN_CLANG_VERSIONS: "3.9"
      - CONAN_CURRENT_PAGE: 1
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-39-page-2:
    docker:
      - image: conanio/clang39
    environment:
      - CONAN_CLANG_VERSIONS: "3.9"
      - CONAN_CURRENT_PAGE: 2
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-39-page-3:
    docker:
      - image: conanio/clang39
    environment:
      - CONAN_CLANG_VERSIONS: "3.9"
      - CONAN_CURRENT_PAGE: 3
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-39-page-4:
    docker:
      - image: conanio/clang39
    environment:
      - CONAN_CLANG_VERSIONS: "3.9"
      - CONAN_CURRENT_PAGE: 4
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-39-page-5:
    docker:
      - image: conanio/clang39
    environment:
      - CONAN_CLANG_VERSIONS: "3.9"
      - CONAN_CURRENT_PAGE: 5
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-39-page-6:
    docker:
      - image: conanio/clang39
    environment:
      - CONAN_CLANG_VERSIONS: "3.9"
      - CONAN_CURRENT_PAGE: 6
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-39-page-7:
    docker:
      - image: conanio/clang39
    environment:
      - CONAN_CLANG_VERSIONS: "3.9"
      - CONAN_CURRENT_PAGE: 7
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-39-page-8:
    docker:
      - image: conanio/clang39
    environment:
      - CONAN_CLANG_VERSIONS: "3.9"
      - CONAN_CURRENT_PAGE: 8
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps

  clang-40-page-1:
    docker:
      - image: conanio/clang40
    environment:
      - CONAN_CLANG_VERSIONS: "4.0"
      - CONAN_CURRENT_PAGE: 1
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-40-page-2:
    docker:
      - image: conanio/clang40
    environment:
      - CONAN_CLANG_VERSIONS: "4.0"
      - CONAN_CURRENT_PAGE: 2
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-40-page-3:
    docker:
      - image: conanio/clang40
    environment:
      - CONAN_CLANG_VERSIONS: "4.0"
      - CONAN_CURRENT_PAGE: 3
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-40-page-4:
    docker:
      - image: conanio/clang40
    environment:
      - CONAN_CLANG_VERSIONS: "4.0"
      - CONAN_CURRENT_PAGE: 4
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-40-page-5:
    docker:
      - image: conanio/clang40
    environment:
      - CONAN_CLANG_VERSIONS: "4.0"
      - CONAN_CURRENT_PAGE: 5
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-40-page-6:
    docker:
      - image: conanio/clang40
    environment:
      - CONAN_CLANG_VERSIONS: "4.0"
      - CONAN_CURRENT_PAGE: 6
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-40-page-7:
    docker:
      - image: conanio/clang40
    environment:
      - CONAN_CLANG_VERSIONS: "4.0"
      - CONAN_CURRENT_PAGE: 7
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-40-page-8:
    docker:
      - image: conanio/clang40
    environment:
      - CONAN_CLANG_VERSIONS: "4.0"
      - CONAN_CURRENT_PAGE: 8
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps

  clang-50-page-1:
    docker:
      - image: conanio/clang50
    environment:
      - CONAN_CLANG_VERSIONS: "5.0"
      - CONAN_CURRENT_PAGE: 1
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-50-page-2:
    docker:
      - image: conanio/clang50
    environment:
      - CONAN_CLANG_VERSIONS: "5.0"
      - CONAN_CURRENT_PAGE: 2
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-50-page-3:
    docker:
      - image: conanio/clang50
    environment:
      - CONAN_CLANG_VERSIONS: "5.0"
      - CONAN_CURRENT_PAGE: 3
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-50-page-4:
    docker:
      - image: conanio/clang50
    environment:
      - CONAN_CLANG_VERSIONS: "5.0"
      - CONAN_CURRENT_PAGE: 4
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-50-page-5:
    docker:
      - image: conanio/clang50
    environment:
      - CONAN_CLANG_VERSIONS: "5.0"
      - CONAN_CURRENT_PAGE: 5
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-50-page-6:
    docker:
      - image: conanio/clang50
    environment:
      - CONAN_CLANG_VERSIONS: "5.0"
      - CONAN_CURRENT_PAGE: 6
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-50-page-7:
    docker:
      - image: conanio/clang50
    environment:
      - CONAN_CLANG_VERSIONS: "5.0"
      - CONAN_CURRENT_PAGE: 7
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps
  clang-50-page-8:
    docker:
      - image: conanio/clang50
    environment:
      - CONAN_CLANG_VERSIONS: "5.0"
      - CONAN_CURRENT_PAGE: 8
      - CONAN_TOTAL_PAGES: 8
      - CONAN_DOCKER_32_IMAGES: 1
    <<: *conan-steps


workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-49-page-1
      - gcc-49-page-2
      - gcc-49-page-3
      - gcc-49-page-4
      - gcc-49-page-5
      - gcc-49-page-6
      - gcc-49-page-7
      - gcc-49-page-8

      - gcc-5-page-1
      - gcc-5-page-2
      - gcc-5-page-3
      - gcc-5-page-4
      - gcc-5-page-5
      - gcc-5-page-6
      - gcc-5-page-7
      - gcc-5-page-8

      - gcc-6-page-1
      - gcc-6-page-2
      - gcc-6-page-3
      - gcc-6-page-4
      - gcc-6-page-5
      - gcc-6-page-6
      - gcc-6-page-7
      - gcc-6-page-8

      - gcc-7-page-1
      - gcc-7-page-2
      - gcc-7-page-3
      - gcc-7-page-4
      - gcc-7-page-5
      - gcc-7-page-6
      - gcc-7-page-7
      - gcc-7-page-8

      - gcc-8-page-1
      - gcc-8-page-2
      - gcc-8-page-3
      - gcc-8-page-4
      - gcc-8-page-5
      - gcc-8-page-6
      - gcc-8-page-7
      - gcc-8-page-8

      - clang-39-page-1
      - clang-39-page-2
      - clang-39-page-3
      - clang-39-page-4
      - clang-39-page-5
      - clang-39-page-6
      - clang-39-page-7
      - clang-39-page-8

      - clang-40-page-1
      - clang-40-page-2
      - clang-40-page-3
      - clang-40-page-4
      - clang-40-page-5
      - clang-40-page-6
      - clang-40-page-7
      - clang-40-page-8

      - clang-50-page-1
      - clang-50-page-2
      - clang-50-page-3
      - clang-50-page-4
      - clang-50-page-5
      - clang-50-page-6
      - clang-50-page-7
      - clang-50-page-8

      - clang-60-page-1
      - clang-60-page-2
      - clang-60-page-3
      - clang-60-page-4
      - clang-60-page-5
      - clang-60-page-6
      - clang-60-page-7
      - clang-60-page-8
