on: [push, pull_request]

env:
  CONAN_USE_DOCKER: 1

jobs:
  clang:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        version: ["3.9", "4.0", "5.0", "6.0", "7.0", "8"]
    env:
        CONAN_CLANG_VERSIONS: ${{matrix.version}}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: install
        run: |
          chmod +x .ci/install.sh
          ./.ci/install.sh
      - name: run
        run: |
          chmod +x .ci/run.sh
          ./.ci/run.sh
