on: [push, pull_request]

jobs:
  gcc:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        version: ["4.9", "5", "6", "7", "8", "9"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: install
        run: |
          chmod +x .ci/install.sh
          ./.ci/install.sh
      - name: run
        env:
            CONAN_GCC_VERSIONS: ${{matrix.version}}
            CONAN_USE_DOCKER: 1
        run: |
          chmod +x .ci/run.sh
          ./.ci/run.sh
