on: [push, pull_request]

jobs:
  MinGW:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        mingwVersion: ["4.9", "6", "7", "8"]
        buildType: [Debug, Release]
        arch: [x86_64]
        threads: [posix]
        include:
          - arch: "x86"
            exceptions: dwarf2
          - arch: "x86_64"
            exceptions: seh
    steps:
      - uses: actions/checkout@v1
        with:
            fetch-depth: 1
      - name: install
        run: |
            set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
            pip install conan --upgrade
            pip install conan_package_tools bincrafters_package_tools
            conan user
      - name: run  
        env:
            CONAN_BUILD_TYPES: ${{matrix.buildType}}
            MINGW_CONFIGURATIONS: ${{matrix.mingwVersion}}@${{matrix.arch}}@${{matrix.exceptions}}@${{matrix.threads}}
            CONAN_BUILD_REQUIRES: "msys2/20161025"
        run: |
            python build.py
